# Generated by Django 3.0.4 on 2020-03-31 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clientIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('number', models.CharField(max_length=12)),
                ('employerName', models.CharField(max_length=300)),
                ('advice', models.TextField()),
                ('partiesInvolved', models.TextField()),
                ('desiredOutcome', models.TextField()),
                ('acceptOutcome', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
