# Generated by Django 3.0.4 on 2020-04-01 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientintake',
            name='author',
        ),
        migrations.AddField(
            model_name='clientintake',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_intake', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='acceptOutcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='desiredOutcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='employerName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='partiesInvolved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
