# Generated by Django 3.0.4 on 2020-04-01 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientintake',
            name='acceptOutcome',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='desiredOutcome',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='employerName',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='number',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='partiesInvolved',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='streetAddress',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='clientintake',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientintake',
            name='entry',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
