# Generated by Django 3.0.4 on 2020-04-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20200331_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='progress',
            field=models.CharField(choices=[('1', 'Client Intake & Engagement Letter Sent'), ('2', 'Strategy and (or) Demand Letter Included'), ('3', 'Final Client Meeting')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='acceptOutcome',
            field=models.TextField(default='', verbose_name='Knowing that there are no guarantees, what final outcome can you reasonably accept?'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='advice',
            field=models.TextField(default='', verbose_name='Briefly explain what you may need advice about or assistance with today'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='desiredOutcome',
            field=models.TextField(default='', verbose_name='Ideally, if things turn out precisely the way you want, what would be the outcome?'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='employerName',
            field=models.CharField(default='', max_length=300, verbose_name='Name of employer or business name if self-employed'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='firstName',
            field=models.CharField(max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='lastName',
            field=models.CharField(max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='number',
            field=models.CharField(max_length=12, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='partiesInvolved',
            field=models.TextField(default='', verbose_name='Are there any other parties involved? (Examples: a friend, an employer, a neighbor, signor of a contract, etc. This should include parties on either side of your issue)'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='streetAddress',
            field=models.CharField(max_length=400, null=True, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='zipCode',
            field=models.IntegerField(null=True, verbose_name='Postal / Zip code'),
        ),
    ]
