# Generated by Django 3.0.4 on 2020-04-01 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20200401_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientintake',
            old_name='author',
            new_name='username',
        ),
        migrations.AddField(
            model_name='clientintake',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
