# Generated by Django 3.0.4 on 2020-04-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20200417_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='number',
            field=models.CharField(default=0, max_length=12, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='zipCode',
            field=models.IntegerField(default=0, verbose_name='Postal / Zip code'),
        ),
    ]
