# Generated by Django 3.0.4 on 2020-04-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20200401_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='status',
            field=models.CharField(default='Sent', max_length=8),
        ),
    ]
