# Generated by Django 3.0.4 on 2020-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20200417_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='number',
            field=models.CharField(default='', max_length=12, verbose_name='Phone number'),
        ),
    ]
