# Generated by Django 3.0.4 on 2020-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_auto_20200401_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientintake',
            name='status',
        ),
        migrations.AddField(
            model_name='clientintake',
            name='progress',
            field=models.CharField(default='Sent', max_length=8),
        ),
    ]
