# Generated by Django 3.0.4 on 2020-04-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20200420_0241'),
        ('Client', '0004_auto_20200420_0541'),
    ]

    operations = [
    ]
