# Generated by Django 3.0.4 on 2020-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20200401_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='progress',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Recevied', 'Recevied'), ('Filed', 'Filed'), ('Resolved', 'Resolved')], default='Submitted', max_length=100),
        ),
    ]
