# Generated by Django 3.0.4 on 2020-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_auto_20200417_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='progress',
            field=models.CharField(choices=[('Submitted', '1'), ('Recevied', '2'), ('Filed', '3'), ('Resolved', '4')], default=1, max_length=100),
        ),
    ]
