# Generated by Django 3.0.4 on 2020-04-20 17:14

import Client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_merge_20200420_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='clientDocs',
            field=models.FileField(null=True, upload_to=Client.models.user_directory_path, verbose_name='Letter of Engagement'),
        ),
        migrations.AlterField(
            model_name='router',
            name='clientDocs1',
            field=models.FileField(null=True, upload_to=Client.models.user_directory_path, verbose_name='Additional Files'),
        ),
        migrations.AlterField(
            model_name='router',
            name='doc2',
            field=models.FileField(null=True, upload_to=Client.models.user_directory_path, verbose_name='Additional Files'),
        ),
        migrations.AlterField(
            model_name='router',
            name='doc3',
            field=models.FileField(null=True, upload_to=Client.models.user_directory_path, verbose_name='Additional Files'),
        ),

    ]
