# Generated by Django 3.0.4 on 2020-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_auto_20200417_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='progress',
            field=models.CharField(choices=[('1', 'Submitted'), ('2', 'Recevied'), ('3', 'Filed'), ('4', 'Resolved')], default=1, max_length=100),
        ),
    ]
