# Generated by Django 3.0.4 on 2020-04-20 17:55

import Client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_auto_20200420_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='clientDocs',
            field=models.FileField(blank=True, null=True, upload_to=Client.models.user_directory_path, verbose_name='Letter of Engagement (Word.docx)'),
        ),
        migrations.AlterField(
            model_name='router',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to=Client.models.user_directory_path, verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='router',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to=Client.models.user_directory_path, verbose_name='Document 3'),
        ),
    ]
