# Generated by Django 3.0.4 on 2020-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_auto_20200417_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='entry',
            field=models.TextField(default='ENTRY_DATA', max_length=100),
        ),
    ]
